author: [Zhuowei,MinecraftDawn,jdeast,d4g33z]
database: false
description: Implementation of the Minecraft Python API
main: fruitjuice.FruitJuicePlugin
name: FruitJuice
startup: postworld
version: '0.4.0'
api-version: 1.13